# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    cert
    sigh(force: true)
    build_app(scheme: "TestingFastlaneVer3")
    upload_to_testflight
  end

lane :getCodeSigning do
  get_certificates           # invokes cert
  get_provisioning_profile   # invokes sigh
  build_app
end
lane :cleanAndBuild do
#ensure_git_branch
version = increasePatchNumber
clear_derived_data
gym(scheme: "TestingFastlaneVer3")
end

lane :increasePatchNumber do
increment_version_number(
  bump_type: "patch" # Automatically increment patch version number
)
end

lane :increaseMinorNumber do
increment_version_number(
  bump_type: "minor" # Automatically increment minor version number
)
end

lane :increaseMajorNumber do
increment_version_number(
  bump_type: "major" # Automatically increment major version number
)
end
end
