name: Tests 
on:
  push:
  pull_request:
    branches: [ develop ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  tests:
    name: Tests 
    runs-on: macos-latest
      
    steps:      
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
            
    - name: Fastlane Action
  # You may pin to the exact commit or the version.
  # uses: maierj/fastlane-action@2121d31315dd0054a407c2c24938ae1fa29b883d
  uses: maierj/fastlane-action@v2.0.1
  with:
    # The lane that should be executed.
    lane: cleanAndBuild
    
