name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: test-fastlane
    runs-on: macos-latest

    steps:
    - name: Checkout
    uses: actions/checkout@v2
    
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
      
    - name: Run tests
      run: fastlane cleanAndBuild
