name: Deploy to Testflight 
on:
  release:
    types: [ created ]
  push:
    branches: [ release ]
  pull_request:
    branches: [ develop ]
jobs:
  deploy:
    name: Deploy
    runs-on: macos-latest
      
    steps:      
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
        
    - name: App Store Connect API
      uses: yuki0n0/action-appstoreconnect-token@v1.0
      with:
        # UUID. Can get from App Store Connect.
        issuer id: e04a730a-511d-42b8-b08f-8783bfa57546
        # Key ID. Can get from App Store Connect.
        key id: L84V95726Q
        # P8 private key. Can get from App Store Connect.
        key: ${{ secrets.P8_PRIVATE_KEY }}
            
    - name: Build & Distribute to Testflight 
      uses: maierj/fastlane-action@v2.0.1
      with:
        lane: 'beta'
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
        RELEASE_VERSION: ${{ github.event.release.tag_name }}
        CHANGELOG: ${{ github.event.release.body }}
